repos:
  -   repo: https://github.com/pre-commit/mirrors-black
      rev: v21.9b0
      hooks:
      -   id: black
  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.3
      hooks:
      -   id: isort
