name: Test and Linting

on:
  push:
    branches:
      - main

jobs:
  container:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PREFECT_CLOUD_API_TOKEN: ${{ secrets.PREFECT_CLOUD_API_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Authenticate with Prefect Cloud
      run: prefect cloud login -k $PREFECT_CLOUD_API_TOKEN

    - name: Run tests
      run: pytest tests

    - name: Run linting
      run: |
        pylint src tests
